name: codeparents
favicon: null
layout_spectrum: 0.6391374736558646
typography_spectrum: 0.17787738610059023
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7308251499198377
  lightness: 0.2603999739512801
  saturation: 0.24638876575045288
  rhythmicContrast: 0.2655077283270657
purpose: []
